/**
 * @fileoverview AI-attribution comment detection.
 *
 * Detects "generated by AI" / "Claude wrote this" style attribution
 * metadata in comments. Source comments must stand on their own
 * merit; AI-attribution leaks process metadata into shipped code.
 *
 * Extracted from the former `comment-quality` umbrella in Phase C1.
 */

import { defineCheck, type CheckViolation } from '@opensip-tools/fitness'

/** Maximum line length for regex matching */
const MAX_LINE_LENGTH = 500

/**
 * Safely truncate a line for regex matching.
 */
function safeLineForRegex(line: string): string {
  return line.length > MAX_LINE_LENGTH ? line.slice(0, MAX_LINE_LENGTH) : line
}

// AI-generation metadata patterns (bounded quantifiers)
const AI_GENERATED_BY_SINGLE_PATTERN =
  /\/\/[^/]{0,200}\b(?:generated|created|written|assisted)\s{1,5}by\s{1,5}(?:ai|chatgpt|claude|copilot|gpt|llm|openai|anthropic|gemini|bard)\b/i
const AI_TOOL_ACTION_SINGLE_PATTERN =
  /\/\/[^/]{0,200}\b(?:ai|chatgpt|claude|copilot|gpt|llm)\s{1,5}(?:generated|created|wrote|suggested|assisted)\b/i
const AI_GENERATED_BY_BLOCK_PATTERN =
  /\/\*{1,5}[^*]{0,200}\b(?:generated|created|written|assisted)\s{1,5}by\s{1,5}(?:ai|chatgpt|claude|copilot|gpt|llm|openai|anthropic|gemini|bard)\b/i

const PATTERNS: RegExp[] = [
  AI_GENERATED_BY_SINGLE_PATTERN,
  AI_TOOL_ACTION_SINGLE_PATTERN,
  AI_GENERATED_BY_BLOCK_PATTERN,
]

const FIX_MESSAGE = 'Remove AI-generation metadata; comments must stand on their own merit'

/**
 * Check: quality/no-ai-attribution
 *
 * Detects AI-attribution metadata in comments.
 */
export const noAiAttribution = defineCheck({
  id: '5b9e7c8a-4f12-4c5d-93f1-1e2a3b4c5d6e',
  slug: 'no-ai-attribution',
  scope: { languages: ['typescript'], concerns: ['backend', 'frontend', 'cli'] },
  contentFilter: 'raw',
  confidence: 'medium',
  description: 'Detects AI-attribution metadata in comments',
  longDescription: `**Purpose:** Source comments must stand on their own merit. AI-attribution metadata ("Generated by Claude", "ChatGPT wrote this") leaks process information into code that has no value to readers and quickly goes stale.

**Detects:** Single-line and block comments containing "generated by AI/Claude/GPT/Copilot/Anthropic/OpenAI/etc." attribution patterns.

**Why it matters:** Comments should explain the code, not its provenance. Tools or models used during authorship belong in commit messages or external metadata, not in source files.`,
  tags: ['maintainability', 'code-quality', 'quality'],
  fileTypes: ['ts', 'tsx'],
  disabled: true,

  analyze(content: string, filePath: string): CheckViolation[] {
    if (!content.includes('//') && !content.includes('/*')) {
      return []
    }

    const violations: CheckViolation[] = []
    const lines = content.split('\n')

    for (const [i, line] of lines.entries()) {
      if (!line) continue
      const safeLine = safeLineForRegex(line)
      for (const pattern of PATTERNS) {
        if (pattern.test(safeLine)) {
          violations.push({
            line: i + 1,
            message: `AI-attribution comment found. ${FIX_MESSAGE}`,
            severity: 'error',
            suggestion: FIX_MESSAGE,
            match: safeLine.trim().slice(0, 60),
            filePath,
          })
          break // one finding per line
        }
      }
    }

    return violations
  },
})
