/**
 * @fileoverview AI-attribution comment detection.
 *
 * Detects "generated by AI" / "Claude wrote this" style attribution
 * metadata in comments. Source comments must stand on their own
 * merit; AI-attribution leaks process metadata into shipped code.
 *
 * Extracted from the former `comment-quality` umbrella in Phase C1.
 *
 * Migrated to defineRegexListCheck (Phase C6 / 2026-05-23 NF2). The
 * original site truncated each line to 500 chars before running the
 * regex; that ReDoS guard is unnecessary here because every pattern
 * already uses bounded quantifiers (`[^/]{0,200}`, `[^*]{0,200}`,
 * `\s{1,5}`), so an unbounded line cannot produce catastrophic
 * backtracking. The `oneViolationPerLine: true` option preserves the
 * original "one finding per line, first matching pattern wins"
 * semantics.
 */

import { defineRegexListCheck } from '@opensip-cli/fitness';

const FIX_MESSAGE = 'Remove AI-generation metadata; comments must stand on their own merit';
const VIOLATION_MESSAGE = `AI-attribution comment found. ${FIX_MESSAGE}`;

/**
 * Check: quality/no-ai-attribution
 *
 * Detects AI-attribution metadata in comments.
 */
export const noAiAttribution = defineRegexListCheck({
  id: '4281da0e-2af1-447b-8a25-1da675f41f56',
  slug: 'no-ai-attribution',
  scope: { languages: ['typescript'], concerns: ['backend', 'frontend', 'cli'] },
  contentFilter: 'raw',
  confidence: 'medium',
  description: 'Detects AI-attribution metadata in comments',
  longDescription: `**Purpose:** Source comments must stand on their own merit. AI-attribution metadata ("Generated by Claude", "ChatGPT wrote this") leaks process information into code that has no value to readers and quickly goes stale.

**Detects:** Single-line and block comments containing "generated by AI/Claude/GPT/Copilot/Anthropic/OpenAI/etc." attribution patterns.

**Why it matters:** Comments should explain the code, not its provenance. Tools or models used during authorship belong in commit messages or external metadata, not in source files.`,
  tags: ['maintainability', 'code-quality', 'quality'],
  fileTypes: ['ts', 'tsx'],
  disabled: true,
  options: {
    // Comments are exactly what this check targets — do NOT skip them.
    skipCommentLines: false,
    // Original site emitted at most one violation per line via `break`
    // after the first matching pattern.
    oneViolationPerLine: true,
  },
  patterns: [
    {
      id: '97fb9199-8a84-448e-9f6b-06eb468f63e9',
      slug: 'ai-generated-by-single',
      regex:
        /\/\/[^/]{0,200}\b(?:generated|created|written|assisted)\s{1,5}by\s{1,5}(?:ai|chatgpt|claude|copilot|gpt|llm|openai|anthropic|gemini|bard)\b/i,
      message: VIOLATION_MESSAGE,
      severity: 'error',
      suggestion: FIX_MESSAGE,
    },
    {
      id: '8ebd2f1a-d146-4906-ac36-921e28d5847f',
      slug: 'ai-tool-action-single',
      regex:
        /\/\/[^/]{0,200}\b(?:ai|chatgpt|claude|copilot|gpt|llm)\s{1,5}(?:generated|created|wrote|suggested|assisted)\b/i,
      message: VIOLATION_MESSAGE,
      severity: 'error',
      suggestion: FIX_MESSAGE,
    },
    {
      id: 'f1d68629-f299-4ee7-94ed-89cc246c57ba',
      slug: 'ai-generated-by-block',
      regex:
        /\/\*{1,5}[^*]{0,200}\b(?:generated|created|written|assisted)\s{1,5}by\s{1,5}(?:ai|chatgpt|claude|copilot|gpt|llm|openai|anthropic|gemini|bard)\b/i,
      message: VIOLATION_MESSAGE,
      severity: 'error',
      suggestion: FIX_MESSAGE,
    },
  ],
});
