/**
 * Dashboard HTML generator — orchestrates all modules into a single self-contained HTML file.
 *
 * Composes CSS, shared JS, and tab-specific JS into one HTML string with all data inlined.
 * Each tool tab (Fitness, Simulation) has subtabs: Sessions, Catalog, Recipes.
 */

// Bundled, type-checked client modules (L4 migration). Generated by
// scripts/bundle-client.mjs from src/client/*.ts; inlined before the legacy
// string emitters so its exposed globals (e.g. `el`, `renderOverview`,
// `renderFitnessTab`) resolve for them and for the render block below. The
// subtab-bar / overview / sessions / checks / recipes / tool-tabs renderers now
// live in that bundle (src/client/*.ts).
import { DASHBOARD_CLIENT_BUNDLE } from './client-bundle.generated.js';
import { projectCatalogToGraphViewModel } from './code-paths/graph-view-model.js';
import { dashboardCodePathsVendorJs } from './code-paths.js';
import { dashboardCss } from './css.js';
import { REPORT_CUP_FAVICON_DATA_URI, REPORT_CUP_HEADER_HTML } from './report-cup-icon.js';
import { listToolTabs } from './tool-tab-registry.js';
import './tool-tabs-registrations.js'; // side-effect: registers fit/sim/graph

import type { StoredSession, GraphCatalog, DeclaredInputs } from '@opensip-cli/contracts';

/**
 * Inputs to the dashboard HTML generator.
 *
 * `sessions` is required; everything else has a sensible default
 * (empty array / null) so a Tool that does not produce a catalog or
 * recipes can call `generateDashboardHtml({ sessions })` and get a
 * working dashboard.
 *
 * Future tool-shaped data — alarm history, dependency graphs, simulation
 * traces — will land as new optional fields on this interface rather
 * than as new positional parameters. That keeps the call site
 * order-independent and the public API source-stable.
 */
export interface DashboardInput {
  sessions: StoredSession[];
  declaredInputs?: DeclaredInputs;
  // Tool-owned catalog data, consumed structurally by the dashboard's
  // renderers (audit 2026-05-29, L1). Typed `unknown[]` because the entry
  // shapes (fitness's CheckCatalogEntry / RecipeCatalogEntry) are tool
  // domain vocabulary owned by the producing tool, not contracts. The
  // dashboard inlines them as JSON and its JS reads fields structurally.
  checkCatalog?: readonly unknown[];
  recipeCatalog?: readonly unknown[];
  graphCatalog?: GraphCatalog | null;
  // Graph-owned catalog data (Plan B). DISTINCT keys from fitness's
  // `checkCatalog`/`recipeCatalog` because the CLI merges every tool's
  // contribution via Object.assign — same key would clobber fitness. The
  // dashboard reads them structurally (entry shapes are graph domain
  // vocabulary owned by @opensip-cli/graph, not contracts).
  graphRuleCatalog?: readonly unknown[];
  graphRecipeCatalog?: readonly unknown[];
  // Simulation-owned catalog data (L6). DISTINCT keys (sim prefix) for the same
  // Object.assign-merge reason; the dashboard's Simulation tab reads them
  // structurally (entry shapes are sim domain vocabulary owned by the sim tool).
  simScenarioCatalog?: readonly unknown[];
  simRecipeCatalog?: readonly unknown[];
  // Yagni-owned catalog data. DISTINCT keys for the Object.assign merge reason.
  yagniSummary?: unknown;
  yagniCatalog?: readonly unknown[];
  editorProtocol?: string | null;
}

// Host-owned catch-all tab for sessions whose `tool` is NOT claimed by any
// registered tool tab (external-adapter scans — gitleaks / osv-scanner / trivy).
// Their worker-forked runtimes are never loaded in-host, so they structurally
// cannot register a `defineToolTab` tab; the four per-tool tabs only bucket their
// own same-tool sessions, leaving adapter findings rendered nowhere. This id /
// label / icon is the single source of truth: the generator emits the tab,
// panel, and render-call, and injects `externalTabId` as a page global so the
// bundled overview row-click handler (client/overview.ts) routes unclaimed-tool
// rows here and the catch-all renderer (client/tool-tabs.ts → renderExternalTab)
// resolves the panel id.
const EXTERNAL_TAB_ID = 'external';
const EXTERNAL_TAB_LABEL = 'External Tools';
// Shield icon (lucide) — external adapters are typically secret/vuln scanners.
const EXTERNAL_TAB_ICON = String.raw`<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"/></svg>`;

// Escape all < and > to prevent script injection in HTML <script> context
function escapeForScriptContext(json: string): string {
  return json.replaceAll('<', String.raw`\u003c`).replaceAll('>', String.raw`\u003e`);
}

// Coerce a session.score into a finite number safe for HTML interpolation
// in the <title> tag. Returns 0 for non-finite values so the rendered
// title remains well-formed even if a legacy or corrupted session row
// somehow carries a non-numeric score.
function coerceScoreForTitle(score: unknown): number {
  const n = Number(score);
  return Number.isFinite(n) ? n : 0;
}

function escapeHtml(value: unknown): string {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function renderDeclaredInputs(input: DeclaredInputs | undefined): string {
  if (input === undefined) return '';
  const pairs = [
    ['CLI', input.cliVersion],
    ['Node', input.nodeVersion],
    ['Package manager', input.packageManager ?? 'unknown'],
    ['Platform', input.platform],
    ['Tool', input.tool],
    ['Engine', input.engineVersion ?? 'unknown'],
    [
      'Baseline',
      input.baselineIdentity === undefined
        ? 'unknown'
        : `${input.baselineIdentity.fingerprintStrategyId}@${input.baselineIdentity.fingerprintStrategyVersion}`,
    ],
  ];
  const chips = pairs
    .map(
      ([label, value]) =>
        `<span class="badge" title="${escapeHtml(label)}">${escapeHtml(label)}: ${escapeHtml(value)}</span>`,
    )
    .join(' ');
  return `<div class="card" style="margin:16px 24px 0;padding:12px 16px"><strong>Run environment</strong><div style="margin-top:8px;display:flex;flex-wrap:wrap;gap:8px">${chips}</div></div>`;
}

/**
 * Serialize an optional value into either a `<script type="application/json">`
 * blob (kind `'json'`) or a JS `const X = …;` literal (kind `'literal'`).
 *
 * Both call sites used to inline the same escape-then-stringify dance;
 * folding them into one helper means the script-context escape is
 * applied uniformly and the null-vs-supplied branching is in one place.
 *
 * - `'json'`: emits `<script type="application/json" id="<id>">…</script>`
 *   when `value` is not null/undefined; emits the empty string otherwise.
 * - `'literal'`: emits `const <id> = …;` always — `null` is rendered as
 *   the JS literal `null`, anything else as `JSON.stringify(value)`.
 */
function serializeOptionalBlob(id: string, value: unknown, kind: 'json' | 'literal'): string {
  switch (kind) {
    case 'json': {
      if (value === null || value === undefined) return '';
      const escaped = escapeForScriptContext(JSON.stringify(value));
      return `<script type="application/json" id="${id}">${escaped}</script>`;
    }
    case 'literal': {
      // Apply the same script-context escape as the 'json' arm — without it,
      // a value containing the literal sequence `</script>` would close the
      // surrounding inline <script> block (JSON.stringify does not escape `<`).
      const rendered =
        value === null || value === undefined
          ? 'null'
          : escapeForScriptContext(JSON.stringify(value));
      return `const ${id} = ${rendered};`;
    }
  }
}

/** Renders a self-contained HTML dashboard string from sessions and catalog inputs. */
export function generateDashboardHtml(input: DashboardInput): string {
  const {
    sessions,
    checkCatalog = [],
    recipeCatalog = [],
    graphCatalog = null,
    graphRuleCatalog = [],
    graphRecipeCatalog = [],
    simScenarioCatalog = [],
    simRecipeCatalog = [],
    yagniSummary = null,
    yagniCatalog = [],
    editorProtocol = null,
    declaredInputs,
  } = input;

  const latest = sessions[0];
  // Coerce score to a finite number before interpolating into the <title>
  // tag — `latest.score` is typed `number` but originates from a SQLite
  // column and a corrupt or legacy row could carry an arbitrary value.
  // Number(NaN-ish) on a string still yields NaN; we substitute 0 to keep
  // the page title well-formed in the pathological case.
  const latestScoreSafe = latest ? coerceScoreForTitle(latest.score) : 0;
  const safeDataJson = escapeForScriptContext(JSON.stringify(sessions));
  const safeCatalogJson = escapeForScriptContext(JSON.stringify(checkCatalog));
  const safeRecipeJson = escapeForScriptContext(JSON.stringify(recipeCatalog));
  const safeGraphRuleCatalogJson = escapeForScriptContext(JSON.stringify(graphRuleCatalog));
  const safeGraphRecipeCatalogJson = escapeForScriptContext(JSON.stringify(graphRecipeCatalog));
  const safeSimScenarioCatalogJson = escapeForScriptContext(JSON.stringify(simScenarioCatalog));
  const safeSimRecipeCatalogJson = escapeForScriptContext(JSON.stringify(simRecipeCatalog));
  const safeYagniSummaryJson = escapeForScriptContext(JSON.stringify(yagniSummary));
  const safeYagniCatalogJson = escapeForScriptContext(JSON.stringify(yagniCatalog));
  const graphCatalogBlock = serializeOptionalBlob('graph-catalog', graphCatalog, 'json');
  // The Visualization view (view-graph.ts) consumes a slim, pre-projected
  // view-model rather than the raw catalog: projection aggregates the
  // function call graph up to PACKAGE nodes + package→package edges (with
  // coupling weights + cross-package SCCs) here at generation time and embeds
  // it as its own JSON blob, sized for the renderer rather than for storage.
  // See code-paths/graph-view-model.ts.
  const graphViewModel = graphCatalog ? projectCatalogToGraphViewModel(graphCatalog) : null;
  const graphViewModelBlock = serializeOptionalBlob('graph-view-model', graphViewModel, 'json');
  const editorProtocolJs = serializeOptionalBlob('EDITOR_PROTOCOL', editorProtocol, 'literal');

  // Tool tabs are registered into a single registry; Overview is a
  // cross-tool aggregate kept fixed at position 0. The HTML tab
  // buttons, panel containers, and the renderXxxTab() invocation list
  // all derive from the same iteration so adding a new tab is a single
  // defineToolTab() call (see tool-tabs-registrations.ts).
  const toolTabs = listToolTabs();
  // Bucket every session whose tool is NOT claimed by a registered tab into the
  // host-owned catch-all "External Tools" tab. Emitted ONLY when such sessions
  // exist so a fit-only repo never shows an empty External Tools tab.
  const claimedTools = new Set(toolTabs.map((t) => t.tool));
  const hasExternalSessions = sessions.some((s) => !claimedTools.has(s.tool));
  const toolTabButtons = [
    ...toolTabs.map((t) => `  <div class="tab" data-tab="${t.id}">${t.icon} ${t.label}</div>`),
    ...(hasExternalSessions
      ? [
          `  <div class="tab" data-tab="${EXTERNAL_TAB_ID}">${EXTERNAL_TAB_ICON} ${EXTERNAL_TAB_LABEL}</div>`,
        ]
      : []),
  ].join('\n');
  const toolTabPanels = [
    ...toolTabs.map((t) => `<div id="panel-${t.id}" class="tab-panel"></div>`),
    ...(hasExternalSessions ? [`<div id="panel-${EXTERNAL_TAB_ID}" class="tab-panel"></div>`] : []),
  ].join('\n');
  const toolTabRenderCalls = [
    ...toolTabs.map((t) => `${t.renderFunctionName}();`),
    ...(hasExternalSessions ? ['renderExternalTab();'] : []),
  ].join('\n');
  // Overview's `tool → badge style` and `tool → tab id` maps, derived from the
  // same registry and injected as page globals so the bundled overview renderer
  // (src/client/overview.ts) reads them as ambient data — the registry
  // derivation stays type-checked Node code rather than a string template (F1/F8).
  const toolBadgeStylesJson = JSON.stringify(
    Object.fromEntries(toolTabs.map((t) => [t.tool, t.badgeStyle])),
  );
  const tabMapJson = JSON.stringify(Object.fromEntries(toolTabs.map((t) => [t.tool, t.id])));

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OpenSIP CLI${latest ? ` — Pass Rate: ${latestScoreSafe}%` : ''}</title>
<link rel="icon" type="image/svg+xml" href="${REPORT_CUP_FAVICON_DATA_URI}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&display=swap" rel="stylesheet">
<style>
${dashboardCss()}
</style>
</head>
<body>

<div class="header">
  <span class="header-icon">${REPORT_CUP_HEADER_HTML}</span>
  <div><h1><span class="brand-open">Open</span>SIP Report</h1></div>
</div>

${renderDeclaredInputs(declaredInputs)}

<div class="tab-bar" id="tab-bar">
  <div class="tab active" data-tab="overview"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/></svg> Overview</div>
${toolTabButtons}
</div>

<div id="panel-overview" class="tab-panel active"></div>
${toolTabPanels}

<div class="footer">Generated by <strong>OpenSIP CLI</strong> &mdash; <a href="https://opensip.ai">opensip.ai</a></div>

${graphCatalogBlock}
${graphViewModelBlock}
<script>
const sessions = ${safeDataJson};
const checkCatalog = ${safeCatalogJson};
const recipeCatalog = ${safeRecipeJson};
const graphRuleCatalog = ${safeGraphRuleCatalogJson};
const graphRecipeCatalog = ${safeGraphRecipeCatalogJson};
const simScenarioCatalog = ${safeSimScenarioCatalogJson};
const simRecipeCatalog = ${safeSimRecipeCatalogJson};
const yagniSummary = ${safeYagniSummaryJson};
const yagniCatalog = ${safeYagniCatalogJson};
${editorProtocolJs}
const fitSessions = sessions.filter(s => s.tool === 'fit');
const simSessions = sessions.filter(s => s.tool === 'sim');
const yagniSessions = sessions.filter(s => s.tool === 'yagni');
// Registry-derived Overview maps (tool → badge style / tab id), consumed as page
// globals by the bundled overview renderer (src/client/overview.ts).
const toolBadgeStyles = ${toolBadgeStylesJson};
const tabMap = ${tabMapJson};
// Host-owned catch-all: sessions whose tool is not claimed by a registered tab
// (external-adapter scans). Rendered in the "External Tools" tab; the overview
// row-click handler routes unclaimed-tool rows to externalTabId.
const externalSessions = sessions.filter(s => !(s.tool in tabMap));
const externalTabId = ${JSON.stringify(EXTERNAL_TAB_ID)};

// The vendored Cytoscape renderer (defines the cytoscape / cytoscapeDagre
// browser globals the Visualization view consumes). Inlined BEFORE the bundle so
// those globals are present; it is a third-party UMD blob, not our client JS.
${dashboardCodePathsVendorJs()}
${DASHBOARD_CLIENT_BUNDLE}

// =======================================================
// RENDER TABS
// =======================================================
renderOverview();
${toolTabRenderCalls}
</script>
</body>
</html>`;
}
