/**
 * @fileoverview Checks must use real, stable UUIDs for their `id` field (not
 * placeholder patterns like a1b2c3d4-9876-4321-... or xxx-000000000001).
 *
 * Per the project's convention (and recent hygiene work), check IDs must be
 * proper promoted UUIDs once the check is real. Placeholder IDs are only for
 * development and must be replaced before "promotion".
 *
 * This is a meta-check on the check definitions themselves.
 */
import { defineCheck, type CheckViolation } from '@opensip-cli/fitness';

const PLACEHOLDER_PATTERNS: RegExp[] = [
  // Legacy patterned IDs from early check authoring (to be replaced with promoted real UUIDs)
  /a1b2c3d4-9876-4321-aaaa-10000000000[12]/,
  /b1c2d3e4-9876-4321-bbbb-200000000001/,
  /c1d2e3f4-9876-4321-cccc-300000000001/,
  /d1e2f3a4-9876-4321-dddd-400000000001/,
  /e1f2a3b4-9876-4321-eeee-500000000001/,
  /e2f3a4b5-1234-4321-eeee-500000000001/,
  /a7f3c1d2-4b5e-4c6a-9d8e-300000000002/,
  /d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a/,
  /e1f2a3b4-c5d6-7e8f-9a0b-1c2d3e4f5a6b/,
  /a8d3c1f2-4b5e-6a7d-8c9e-0f1a2b3c4d5e/,
  /a7f1c2d3-4e5b-6a7c-8d9e-0f1a2b3c4d5e/,
  /b1e7c2a0-4d6f-4a8b-9c3e-1f2a3b4c5d6e/,
  /f3a2c1d4-5b6e-4f70-8a9c-0d1e2f3a4b5c/,
  /c7f3e1a8-4b2d-4e6a-9f1c-3a8d5e2b7c04/,
  /f3a4b5c6-d7e8-9f0a-1b2c-3d4e5f6a7b8c/,
  /7f3c2a1b-8e9d-4f0a-9c1d-2e3f4a5b6c7d/,
  /a7d3e1f2-8b4c-4d9e-af12-6c8b3d7e9f01/,
  /b9572b0b-8693-4723-aaaa-9221105e4ebc/,
  /b7f3a1d2-94e8-4c5f-8b6a-3e2d1f9c8a7b/,
  /6f9b3c2d-e4a5-4b6c-8d7e-8f9a0b1c2d3e/,
  /5e8a2b1c-d3f4-4a5b-9c6d-7e8f9a0b1c2d/,
  /5b9e7c8a-4f12-4c5d-93f1-1e2a3b4c5d6e/,
  /4c2e1a8b-9f7d-4e3a-8b6c-1d0f2a3b4c5e/,
  /c7e4a1f2-3b6d-4e08-9a51-2f8c4d0b7e93/,
  /c7e2d4a1-5f8b-4c3e-9d1a-6b0f7e8a2c4d/,
  /7b3a9e1c-8d2f-4a5b-9c6d-0e1f2a3b4c5d/,
  /a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d/,
  /9a2a9d7a-2e40-4adf-b682-534c3412d4da/,
  // catch other obvious patterned or zero-heavy ones (low entropy placeholders)
  /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-0{10}[0-9a-f]{2}/,
  /[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-aaaa-\d{12}/,
  // common test/demo sequential families
  /[0-9a-f]1[0-9a-f]2[0-9a-f]3[0-9a-f]4-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i,
];

const CHECK_ID_REGEX =
  /id:\s*['"]([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})['"]/g;

export function analyzeNoPlaceholderCheckIds(content: string, filePath: string): CheckViolation[] {
  // Only skip real test sources (the meta's own tests + other check tests).
  // We intentionally *do* analyze content under __fixtures__ when the harness
  // exercises our 'violation' fixture (so coverage passes). Other checks' demo
  // sample-check.ts files are protected by the isDemoExample guard below.
  if (filePath.includes('.test.')) {
    return [];
  }

  const violations: CheckViolation[] = [];
  CHECK_ID_REGEX.lastIndex = 0;
  let match;

  while ((match = CHECK_ID_REGEX.exec(content)) !== null) {
    const id = match[1];

    // Skip obvious illustrative/demo IDs that appear inside quality checks as examples
    // (e.g. no-raw-regex-on-code, no-process-artifacts, no-ai-attribution, no-eval etc).
    // These files legitimately contain "bad example" check definitions for pedagogical reasons.
    const before = content.slice(0, match.index);
    const lineStart = before.lastIndexOf('\n') + 1;
    const lineEnd = content.indexOf('\n', match.index);
    const lineText = content.slice(lineStart, lineEnd === -1 ? content.length : lineEnd);
    const context = before.slice(-200) + lineText;

    const hasDemoMarker =
      /(?:example|sample|bad|placeholder|illustrative|demo|test id|aaaaaaaa|00000000-0000|promoted stable ID)/i.test(
        context,
      );
    // Detect the well-known all-same test/demo UUIDs (e.g. aaaaaaaa-0000... or all-0 / all-1) by looking at the extracted ID value.
    // This is much cheaper and lower complexity than a complex source regex.
    const normalized = id.replace(/-/g, '');
    const isAllSameDemoId = /^(?:0{32}|1{32}|a{32})$/i.test(normalized);
    const isDemoExample = hasDemoMarker || isAllSameDemoId;

    const knownPromotedMetaIds = new Set([
      'f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c', // this meta-check itself
      'c9f2e1a3-7b5d-4f8e-9c1a-2d3e4f5a6b7c', // tool-contract-version-policy
    ]);

    if (
      !isDemoExample &&
      !knownPromotedMetaIds.has(id.toLowerCase()) &&
      PLACEHOLDER_PATTERNS.some((p) => p.test(id))
    ) {
      const line = before.split('\n').length;
      violations.push({
        message: `Check ID '${id}' appears to be a placeholder or patterned ID. Use a real stable UUID (promoted ID).`,
        severity: 'error',
        line,
        suggestion:
          'Replace with a proper UUID (e.g. generated by uuidgen or an online tool). Update any @fitness-ignore-file directives or tests that reference the old ID. See ADR-0046 and the hygiene work for context.',
      });
    }
  }

  return violations;
}

export const noPlaceholderCheckIds = defineCheck({
  id: 'f1a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c', // promoted stable ID for this meta-check (see analyze guard)
  slug: 'no-placeholder-check-ids',
  description:
    'Check definitions must use real stable UUIDs for their `id` (not placeholder patterns)',
  scope: { languages: ['typescript'], concerns: ['backend'] },
  tags: ['architecture', 'checks', 'meta'],
  fileTypes: ['ts', 'tsx'],
  contentFilter: 'strip-strings',
  analyze: (content, filePath) => analyzeNoPlaceholderCheckIds(content, filePath),
});
