/**
 * @fileoverview Display entries for quality checks
 */

import type { CheckDisplayEntry } from './types.js'

/** Quality check display entries (sorted alphabetically by slug) */
export const QUALITY_DISPLAY = Object.freeze<Record<string, CheckDisplayEntry>>({
  'a11y-form-labels': ['\u267F', 'A11y Form Labels'],
  'a11y-semantic-html': ['\u267F', 'A11y Semantic HTML'],
  'accessible-touchables': ['\u267F', 'Accessible Touchables'],
  'api-contract-validation': ['\uD83D\uDD0C', 'API Contract Validation'],
  'api-response-validation': ['\uD83D\uDD0C', 'API Response Validation'],
  'array-validation': ['\uD83D\uDCE6', 'Array Parameter Validation'],
  'async-state-pattern': ['\u23F3', 'Async State Pattern'],
  'async-waterfall-detection': ['\u26A1', 'Async Waterfall Detection'],
  'centralized-input-sanitization': ['\uD83D\uDEE1\uFE0F', 'Centralized Input Sanitization'],
  'clean-code-function-parameters': ['\uD83C\uDFAF', 'Function Parameter Count (Clean Code)'],
  'clean-code-naming-quality': ['\uD83D\uDCDD', 'Naming Quality (Clean Code)'],
  'comment-quality': ['\uD83D\uDCAC', 'Comment Quality'],
  'database-index-coverage': ['\uD83D\uDDC4\uFE0F', 'Database Index Coverage'],
  'database-schema-validation': ['\uD83D\uDDC4\uFE0F', 'Database Schema Validation'],
  'dead-code': ['\u2620\uFE0F', 'Dead Code'],
  'dependency-security-audit': ['\uD83D\uDD12', 'Dependency Security Audit'],
  'dependency-version-consistency': ['\uD83D\uDCE6', 'Dependency Version Consistency'],
  'dispose-pattern-completeness': ['\uD83E\uDDF9', 'Dispose Pattern Completeness'],
  'duplicate-utility-functions': ['\uD83D\uDD0D', 'Duplicate Utility Functions'],
  'dynamodb-scan-detection': ['\uD83D\uDDC4\uFE0F', 'DynamoDB Scan Detection'],
  'error-handling-quality': ['\u26A0\uFE0F', 'Error Handling Quality'],
  'eslint-justifications': ['\uD83D\uDD0D', 'ESLint Justifications'],
  'expo-vector-icons': ['\uD83D\uDCF1', 'Expo Vector Icons'],
  'fastify-route-validation': ['\uD83D\uDD0C', 'Fastify Route Validation'],
  'fastify-schema-coverage': ['\uD83D\uDD0C', 'Fastify Schema Coverage'],
  'file-headers': ['\uD83D\uDCC4', 'File Headers'],
  'financial-transaction-ordering': ['\uD83D\uDDC4\uFE0F', 'Financial Transaction Ordering'],
  'fitness-ignore-hygiene': ['\uD83E\uDDF9', 'Fitness Ignore Hygiene'],
  'flashlist-enforcement': ['\u26A1', 'FlashList Enforcement'],
  'frontend-client-boundary-placement': ['\uD83C\uDFAF', 'Frontend Client Boundary Placement'],
  'graphql-offset-pagination': ['\uD83D\uDD0C', 'GraphQL Offset Pagination'],
  'image-optimization': ['\uD83D\uDDBC\uFE0F', 'Image Optimization'],
  'in-memory-repository-detection': ['\uD83D\uDCBE', 'In-Memory Repository Detection'],
  'incomplete-regex-escaping': ['\uD83D\uDD12', 'Incomplete Regex Escaping'],
  'lazy-loading': ['\u26A1', 'Lazy Loading (Fail Fast)'],
  'lifecycle-cleanup-enforcement': ['\uD83E\uDDF9', 'Lifecycle Cleanup Enforcement'],
  'logger-event-name-format': ['\uD83D\uDCCA', 'Logger Event Name Format'],
  'memo-list-items': ['\u26A1', 'Memo List Items'],
  'missing-input-validation': ['\uD83D\uDEE1\uFE0F', 'Missing Input Validation'],
  'mutable-exported-constants': ['\uD83D\uDD12', 'Mutable Exported Constants'],
  'navigation-typing': ['\uD83D\uDCF1', 'Navigation Typing'],
  'no-any-types': ['\uD83D\uDCD8', 'No Any Types'],
  'no-console-log': ['\uD83D\uDEAB', 'No Console Log'],
  'no-direct-audit-logging': ['\uD83D\uDCCA', 'No Direct Audit Logging'],
  'no-hardcoded-correlation-id': ['\uD83D\uDD17', 'No Hardcoded Correlation Id'],
  'no-inline-functions': ['\u26A1', 'No Inline Functions'],
  'no-markdown-references': ['\uD83D\uDCDD', 'No Markdown References'],
  'no-raw-regex-on-code': ['\uD83D\uDD0D', 'No Raw Regex On Code'],
  'no-non-null-assertions': ['\uD83D\uDEE1\uFE0F', 'No Non-Null Assertions'],
  'no-window-alert': ['\uD83D\uDEAB', 'No Window Alert'],
  'null-safety': ['\uD83D\uDEE1\uFE0F', 'Null/Undefined Safety'],
  'numeric-validation': ['\uD83D\uDD22', 'Numeric Parameter Validation'],
  'openapi-response-coverage': ['\uD83D\uDD0C', 'OpenAPI Response Coverage'],
  'openapi-type-source': ['\uD83D\uDD0C', 'OpenAPI Type Source'],
  'performance-anti-patterns': ['\u26A1', 'Performance Anti-Patterns'],
  'pii-exposure-in-logs': ['\uD83D\uDD12', 'PII Exposure in Logs'],
  'pino-serializer-coverage': ['\uD83D\uDCCA', 'Pino Serializer Coverage'],
  'platform-checks': ['\uD83D\uDCF1', 'Platform Checks'],
  'postgres-n-plus-one': ['\uD83D\uDDC4\uFE0F', 'Postgres N+1 Detection'],
  'pre-launch-clean-codebase': ['\uD83E\uDDF9', 'Pre-Launch Clean Codebase'],
  'result-pattern-consistency': ['\uD83D\uDCCB', 'Result Pattern Consistency'],
  'security-scan-suite': ['\uD83D\uDD12', 'Security Scan Suite'],
  'semgrep-justifications': ['\uD83D\uDD0D', 'Semgrep Justifications'],
  'silent-early-returns': ['\uD83D\uDD0D', 'Silent Early Returns'],
  'stream-buffer-size-limits': ['\uD83D\uDEE1\uFE0F', 'Stream Buffer Size Limits'],
  'stubbed-implementation-detection': ['\uD83D\uDD0D', 'Stubbed Implementation Detection'],
  'test-only-frontend-modules': ['\uD83E\uDDEA', 'Test-Only Frontend Modules'],
  'test-only-implementations': ['\uD83E\uDDEA', 'Test-Only Implementations'],
  'throws-documentation': ['\uD83D\uDCDD', 'Missing @throws JSDoc Detection'],
  'toctou-race-condition': ['\u26A1', 'TOCTOU Race Condition Detection'],
  'todo-comments': ['\uD83D\uDCDD', 'TODO Comments'],
  'typeorm-n-plus-one': ['\uD83D\uDDC4\uFE0F', 'TypeORM N+1 Detection'],
  'typescript-directive-hygiene': ['\uD83D\uDCD8', 'TypeScript Directive Hygiene'],
  'typescript-frontend': ['\uD83D\uDCD8', 'TypeScript Frontend'],
  'unused-config-options': ['\u2699\uFE0F', 'Unused Configuration Options'],
  'zod-openapi-sync': ['\uD83D\uDD0C', 'Zod OpenAPI Sync'],
})
