// GENERATED by scripts/build-adapter-catalog.mjs — DO NOT EDIT BY HAND.
// Run `pnpm adapter-catalog` to regenerate; `pnpm adapter-catalog:check` gates drift.
// Source of truth: each adapter's tool.ts → opensipTools (build-tool-command-manifests).

/** One installable first-party External Tool Adapter, projected from its manifest. */
export interface FirstPartyAdapter {
  /** npm package to `opensip tools install` (e.g. `@opensip-cli/tool-cppcheck`). */
  readonly pkg: string;
  /** The tool id / primary command verb (`cppcheck`). */
  readonly id: string;
  /** The install-and-run hint command (`opensip cppcheck`). */
  readonly command: string;
  readonly description: string;
  readonly network: 'local-only' | 'networked';
  /** Canonical language ids the scanner covers; `[]` = polyglot (matches every --lang). */
  readonly languages: readonly string[];
  readonly aliases: readonly string[];
}

export const FIRST_PARTY_ADAPTERS: readonly FirstPartyAdapter[] = [
  {
    pkg: '@opensip-cli/tool-ast-grep',
    id: 'ast-grep',
    command: 'opensip ast-grep',
    description: "External Tool Adapter for ast-grep — wraps the ast-grep structural search scanner as an opensip-cli tool",
    network: 'local-only',
    languages: [],
    aliases: ['sg'],
  },
  {
    pkg: '@opensip-cli/tool-bandit',
    id: 'bandit',
    command: 'opensip bandit',
    description: "External Tool Adapter for Bandit — wraps Python security scanning as an opensip-cli tool",
    network: 'local-only',
    languages: ['python'],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-cargo-clippy',
    id: 'cargo-clippy',
    command: 'opensip cargo-clippy',
    description: "External Tool Adapter for cargo clippy — wraps Rust lint diagnostics as an opensip-cli tool. Determinism caveat: cargo clippy only re-emits diagnostics for crates it recompiles; a warm target/ cache can yield zero findings. Use a cold cache or set CARGO_TARGET_DIR for stable --gate-compare rechecks.",
    network: 'local-only',
    languages: ['rust'],
    aliases: ['clippy'],
  },
  {
    pkg: '@opensip-cli/tool-cargo-deny',
    id: 'cargo-deny',
    command: 'opensip cargo-deny',
    description: "External Tool Adapter for cargo-deny — wraps Rust dependency policy checks as an opensip-cli tool",
    network: 'networked',
    languages: ['rust'],
    aliases: ['deny'],
  },
  {
    pkg: '@opensip-cli/tool-cppcheck',
    id: 'cppcheck',
    command: 'opensip cppcheck',
    description: "External Tool Adapter for Cppcheck — wraps C/C++ static analysis as an opensip-cli tool",
    network: 'local-only',
    languages: ['cpp'],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-dependency-check',
    id: 'dependency-check',
    command: 'opensip dependency-check',
    description: "External Tool Adapter for OWASP Dependency-Check — wraps dependency vulnerability scanning as an opensip-cli tool",
    network: 'local-only',
    languages: [],
    aliases: ['owasp-dependency-check'],
  },
  {
    pkg: '@opensip-cli/tool-gitleaks',
    id: 'gitleaks',
    command: 'opensip gitleaks',
    description: "External Tool Adapter for Gitleaks — wraps the gitleaks secret scanner as an opensip-cli tool (opensip gitleaks / opensip secrets)",
    network: 'local-only',
    languages: [],
    aliases: ['secrets'],
  },
  {
    pkg: '@opensip-cli/tool-golangci-lint',
    id: 'golangci-lint',
    command: 'opensip golangci-lint',
    description: "External Tool Adapter for golangci-lint — wraps golangci-lint as an opensip-cli tool",
    network: 'local-only',
    languages: ['go'],
    aliases: ['golangci'],
  },
  {
    pkg: '@opensip-cli/tool-govulncheck',
    id: 'govulncheck',
    command: 'opensip govulncheck',
    description: "External Tool Adapter for govulncheck — wraps Go vulnerability scanning as an opensip-cli tool",
    network: 'networked',
    languages: ['go'],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-osv-scanner',
    id: 'osv-scanner',
    command: 'opensip osv-scanner',
    description: "External Tool Adapter for OSV-Scanner — wraps the osv-scanner dependency vulnerability scanner as an opensip-cli tool (opensip osv-scanner / opensip osv)",
    network: 'networked',
    languages: [],
    aliases: ['osv'],
  },
  {
    pkg: '@opensip-cli/tool-pip-audit',
    id: 'pip-audit',
    command: 'opensip pip-audit',
    description: "External Tool Adapter for pip-audit — wraps Python dependency vulnerability auditing as an opensip-cli tool",
    network: 'networked',
    languages: ['python'],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-pmd',
    id: 'pmd',
    command: 'opensip pmd',
    description: "External Tool Adapter for PMD — wraps Java source analysis as an opensip-cli tool",
    network: 'local-only',
    languages: ['java'],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-ruff',
    id: 'ruff',
    command: 'opensip ruff',
    description: "External Tool Adapter for Ruff — wraps ruff check as an opensip-cli tool",
    network: 'local-only',
    languages: ['python'],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-semgrep',
    id: 'semgrep',
    command: 'opensip semgrep',
    description: "External Tool Adapter for Semgrep — wraps the semgrep scanner as an opensip-cli tool",
    network: 'networked',
    languages: [],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-spotbugs',
    id: 'spotbugs',
    command: 'opensip spotbugs',
    description: "External Tool Adapter for SpotBugs — wraps Java bytecode analysis as an opensip-cli tool",
    network: 'local-only',
    languages: ['java'],
    aliases: [],
  },
  {
    pkg: '@opensip-cli/tool-trivy',
    id: 'trivy',
    command: 'opensip trivy',
    description: "External Tool Adapter for Trivy — wraps the trivy vulnerability + misconfiguration scanner as an opensip-cli tool (opensip trivy)",
    network: 'local-only',
    languages: [],
    aliases: [],
  },
];
