/** Regex patterns and allowlists for interface-implementation-consistency. */

export const INTERFACE_PATTERN =
  /^(?:export\s+)?interface\s+(\w+)(?:<[^>]{1,200}>)?(?:\s+extends\s+([\w,\s<>]+))?/;

// eslint-disable-next-line sonarjs/slow-regex -- anchored line match with bounded prefix
export const INTERFACE_EXTENDS_CONTINUATION = /^\s{0,40}extends\s+([\w,\s<>]+?)\s*\{?\s*$/;

export const CLASS_PATTERN =
  // eslint-disable-next-line sonarjs/regex-complexity -- single regex captures class name + optional extends + optional implements
  /^(?:export\s+)?class\s+(\w+)(?:\s+extends\s+\w+(?:<[^>]{1,200}>)?)?(?:\s+implements\s+([\w,\s<>]+))?/;

export const METHOD_IN_INTERFACE_PATTERN = /^\s{0,20}(\w+)\??\s{0,5}\(/;

export const METHOD_IN_CLASS_PATTERN =
  /^\s{0,20}(?:(?:public|private|protected)\s+)?(?:async\s+)?(?:static\s+)?(\w+)\s{0,5}\(/;

export const STATIC_MODIFIER_PATTERN =
  /^\s{0,20}(?:(?:public|private|protected)\s+)?(?:async\s+)?static\s+\w+\s{0,5}\(/;

export const VISIBILITY_MODIFIER_PATTERN = /^(?:public|protected)\s/;
export const ASYNC_STATIC_METHOD_PATTERN = /^(?:async|static)\s{1,5}[a-zA-Z_]\w{0,99}\s{0,5}\(/;
export const TYPE_ANNOTATION_PATTERN = /\):\s{0,5}[a-zA-Z]/;
export const METHOD_BODY_PATTERN = /\)\s{0,5}\{/;
export const CLASS_LEVEL_METHOD_PATTERN = /^[a-zA-Z_]\w{0,99}\s{0,5}\(/;

export const JS_KEYWORDS = new Set([
  'if',
  'else',
  'while',
  'for',
  'do',
  'switch',
  'case',
  'break',
  'continue',
  'return',
  'throw',
  'try',
  'catch',
  'finally',
  'new',
  'delete',
  'typeof',
  'instanceof',
  'void',
  'in',
  'of',
  'function',
  'class',
  'extends',
  'super',
  'this',
  'import',
  'export',
  'default',
  'const',
  'let',
  'var',
  'await',
  'yield',
  'static',
  'get',
  'set',
  'async',
]);

export const ALLOWED_EXTRA_METHODS = new Set([
  'dispose',
  'destroy',
  'cleanup',
  'close',
  'shutdown',
  'terminate',
  'initialize',
  'init',
  'setup',
  'configure',
  'start',
  'stop',
  'toJSON',
  'toString',
  'valueOf',
  'clone',
  'copy',
  'getStatus',
  'getStats',
  'getHealthStatus',
  'getMetrics',
  'getSuccessRate',
  'subscribe',
  'unsubscribe',
  'publish',
  'emit',
  'on',
  'off',
  'once',
  'listeners',
  'recordMetric',
  'recordMetrics',
  'flush',
  'recordActivity',
  'exists',
  'validate',
  'isValid',
  'isExpired',
  'isEnabled',
  'validateRecipient',
  'send',
  'receive',
  'healthCheck',
  'isHealthy',
  'getDeliveryStatus',
  'trace',
  'debug',
  'info',
  'warn',
  'error',
  'fatal',
  'log',
  'authenticate',
  'refresh',
  'revoke',
  'invalidate',
  'invalidateAll',
  'clearCache',
  'warmCache',
  'getCacheStats',
  'getCacheStatistics',
  'getConfig',
  'clear',
  'reset',
  'resetMetrics',
  'getInstance',
  'isInitialized',
  'getInitializationState',
  'getName',
  'getLogLevel',
  'hasTarget',
  'getFilePath',
  'getLogGroupName',
  'listDomains',
  'listPolicies',
  'isRegistered',
  'create',
  'createWithStoreConfig',
  'createStore',
  'createAlgorithmStrategy',
  'createStoreStrategy',
  'createValidationStrategy',
  'getProviderInstance',
  'add',
  'remove',
  'getChildren',
  'getComponentInfo',
  'getMostUsedFallback',
  'hasHealthCheck',
  'hasFallback',
  'isSensitiveField',
  'recommendStrategy',
  'supportsTimestamp',
  'getConnectionStatus',
  'updateConnectionStatus',
  'getPermissions',
  'addPermission',
  'removePermission',
  'getHealthCheckError',
  'getAllEvents',
  'archiveEvents',
  'listObjects',
  'setProvider',
  'setSecret',
  'deleteSecret',
  'getAllSessions',
  'createSession',
  'query',
  'getEventCount',
  'size',
  'createInvalidation',
  'getInvalidation',
  'waitForInvalidation',
  'createRateLimiter',
  'fromConfig',
  'createCacheKey',
  'toEnvVarName',
]);

export const TEST_DOUBLE_CLASS_NAME_PATTERN = /^(Fake|Mock|Stub|Spy)[A-Z]/;