import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';

const { renderAgentsMd } = await import('../build-agents-md.mjs');

const REPO = join(dirname(fileURLToPath(import.meta.url)), '../..');
const CANONICAL_H1 = '# CLAUDE.md - AI Agent Guidance for OpenSIP CLI';
const MIRROR_H1 = '# AGENTS.md - AI Agent Guidance for OpenSIP CLI';

describe('renderAgentsMd', () => {
  it('swaps only the H1 heading and inserts a generated banner', () => {
    const src = `${CANONICAL_H1}\n\nBody line one.\nBody line two.\n`;
    const out = renderAgentsMd(src);
    const lines = out.split('\n');
    assert.equal(lines[0], MIRROR_H1);
    assert.match(lines[1], /Generated by scripts\/build-agents-md\.mjs/);
    assert.match(lines[2], /pnpm agents:build/);
    // Everything after the H1 (the body) is preserved byte-for-byte.
    assert.ok(out.endsWith('\n\nBody line one.\nBody line two.\n'));
  });

  it('is idempotent-safe: the body carries no CLAUDE.md self-reference', () => {
    // A pure H1 swap is only correct because the source body never says "CLAUDE.md".
    const src = readFileSync(join(REPO, 'CLAUDE.md'), 'utf8');
    const body = src.slice(src.indexOf('\n'));
    assert.ok(
      !body.includes('CLAUDE.md'),
      'CLAUDE.md body must not reference itself, or the mirror would be wrong in AGENTS.md',
    );
  });

  it('throws loudly if CLAUDE.md is retitled (guards silent wrong mirrors)', () => {
    const src = `# Some Other Title\n\nBody.\n`;
    assert.throws(() => renderAgentsMd(src), /not the expected heading/);
  });

  it('matches the committed AGENTS.md (mirror is in sync)', () => {
    const src = readFileSync(join(REPO, 'CLAUDE.md'), 'utf8');
    const committed = readFileSync(join(REPO, 'AGENTS.md'), 'utf8');
    assert.equal(
      renderAgentsMd(src),
      committed,
      'AGENTS.md is stale — run `pnpm agents:build` and commit.',
    );
  });
});
