import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

import {
  profileConfigPaths,
  renderSupportedPlatformsDoc,
  validateSupportRows,
} from '../build-supported-platforms-doc.mjs';
import {
  PLATFORM_SUPPORT_CONTRACT_VERSION,
  PLATFORM_SUPPORT_ROWS,
} from '../../packages/core/dist/index-lib.js';

const REPO_ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const PUBLIC_DOC = join(REPO_ROOT, 'docs/public/70-reference/17-supported-platforms.md');
const WEB_DOC = join(REPO_ROOT, 'docs/web-generated/70-reference/17-supported-platforms.md');
const releaseVersion = () =>
  `v${JSON.parse(readFileSync(join(REPO_ROOT, 'package.json'), 'utf8')).version}`;

const BASE_TUPLE = {
  osPlatform: 'darwin',
  osName: 'macOS',
  osVersionMajor: 26,
  osVersionRange: '26.x',
  kernelName: 'Darwin',
  kernelVersionMajor: 25,
  kernelVersionRange: '25.x',
  nodeVersionMajor: 24,
  nodeAbi: '137',
  npmVersionMajor: 11,
  filesystemType: 'apfs',
  caseSensitive: false,
  installChannels: ['npm-exact-version', 'install-sh'],
};

const PREVIEW_ROW = {
  id: 'macos-26-arm64-node24-npm11-v1',
  status: 'preview',
  tuple: { ...BASE_TUPLE, arch: 'arm64' },
  profile: { id: 'macos-26-arm64-node24-npm11-v1', version: 1 },
  docsPath: 'docs/public/70-reference/17-supported-platforms.md',
  docsUrl: 'https://opensip.ai/docs/opensip-cli/70-reference/17-supported-platforms',
  evidence: { artifact: 'opensip-cli-macos-qualification.v1.json', url: null },
  notes: 'Apple Silicon macOS 26 preview.',
};

const INTEL_ROW = {
  id: 'macos-26-intel-unsupported',
  status: 'unsupported',
  tuple: { ...BASE_TUPLE, arch: 'x64' },
  docsPath: 'docs/public/70-reference/17-supported-platforms.md',
  docsUrl: 'https://opensip.ai/docs/opensip-cli/70-reference/17-supported-platforms',
  notes: 'Intel/x64 macOS is intentionally excluded: no Intel GA evidence.',
};

const ROWS = [PREVIEW_ROW, INTEL_ROW];

test('renders macOS as preview and Intel as unsupported (never a false supported claim)', () => {
  const doc = renderSupportedPlatformsDoc(ROWS, 1, 'v0.7.0');
  // Frontmatter + banner.
  assert.match(doc, /^---\nstatus: current\n/u);
  assert.match(doc, /Generated by scripts\/build-supported-platforms-doc\.mjs/u);
  // The preview row renders `preview`, not `supported`.
  assert.match(doc, /`macos-26-arm64-node24-npm11-v1` \| `preview`/u);
  assert.match(doc, /`macos-26-intel-unsupported` \| `unsupported`/u);
  // macOS row must never be labeled a supported match anywhere in the matrix.
  assert.doesNotMatch(doc, /`macos-26-arm64-node24-npm11-v1` \| `supported`/u);
  // Contract version + the four-status vocabulary.
  assert.match(doc, /contract version: \*\*1\*\*/u);
  for (const status of ['supported', 'preview', 'unqualified', 'unsupported']) {
    assert.ok(doc.includes(`| \`${status}\``), `vocabulary must define ${status}`);
  }
  // "engines is not support" guidance is present.
  assert.match(doc, /`engines` is not a support claim/u);
});

test('is deterministic (byte-stable) for the same registry + version', () => {
  assert.equal(
    renderSupportedPlatformsDoc(ROWS, 1, 'v0.7.0'),
    renderSupportedPlatformsDoc(ROWS, 1, 'v0.7.0'),
  );
});

test('profileConfigPaths dedups and sorts by acceptance-profile id', () => {
  assert.deepEqual(profileConfigPaths(ROWS), [
    '.config/platform-acceptance/macos-26-arm64-node24-npm11-v1.json',
  ]);
});

test('validateSupportRows rejects an empty registry', () => {
  assert.throws(() => validateSupportRows([]), /registry is empty/u);
});

test('validateSupportRows rejects duplicate ids', () => {
  assert.throws(
    () => validateSupportRows([PREVIEW_ROW, PREVIEW_ROW]),
    /duplicate platform-support row id/u,
  );
});

test('validateSupportRows rejects overlapping tuples', () => {
  const clash = { ...INTEL_ROW, id: 'other', tuple: { ...BASE_TUPLE, arch: 'arm64' } };
  assert.throws(
    () => validateSupportRows([PREVIEW_ROW, clash]),
    /overlapping platform-support rows/u,
  );
});

test('validateSupportRows rejects an unknown status', () => {
  assert.throws(
    () => validateSupportRows([{ ...PREVIEW_ROW, status: 'beta' }]),
    /unknown status 'beta'/u,
  );
});

test('validateSupportRows rejects a missing docs link', () => {
  assert.throws(() => validateSupportRows([{ ...PREVIEW_ROW, docsUrl: '' }]), /missing docs link/u);
});

test('validateSupportRows rejects an unsupported row without a reason', () => {
  assert.throws(
    () => validateSupportRows([{ ...INTEL_ROW, notes: '   ' }]),
    /unsupported row without a reason/u,
  );
});

test('validateSupportRows rejects a preview row without a profile', () => {
  const noProfile = { ...PREVIEW_ROW };
  delete noProfile.profile;
  assert.throws(
    () => validateSupportRows([noProfile]),
    /preview row missing a qualification profile link/u,
  );
});

test('validateSupportRows rejects a supported row missing evidence/qualification', () => {
  const supportedNoEvidence = {
    ...PREVIEW_ROW,
    status: 'supported',
    evidence: { artifact: 'x.json', url: null },
  };
  assert.throws(
    () => validateSupportRows([supportedNoEvidence]),
    /supported row missing a published evidence link/u,
  );
  const supportedNoQualification = {
    ...PREVIEW_ROW,
    status: 'supported',
    evidence: { artifact: 'x.json', url: 'https://example/evidence' },
  };
  assert.throws(
    () => validateSupportRows([supportedNoQualification]),
    /supported row missing exact qualification metadata/u,
  );
});

// ---------------------------------------------------------------------------
// Golden render of each status from fixtures (no timestamps in the render args).
// ---------------------------------------------------------------------------

const SUPPORTED_ROW = {
  ...PREVIEW_ROW,
  status: 'supported',
  evidence: {
    artifact: 'opensip-cli-macos-qualification.v1.json',
    url: 'https://example.test/evidence/v0.7.0',
  },
  qualification: {
    consecutiveDailyPasses: 14,
    qualifiedVersion: '0.7.0',
    qualifiedAt: '2026-08-01T00:00:00.000Z',
  },
};

const UNQUALIFIED_ROW = {
  id: 'macos-15-arm64-unqualified',
  status: 'unqualified',
  tuple: { ...BASE_TUPLE, arch: 'arm64', osVersionMajor: 15, osVersionRange: '15.x' },
  docsPath: 'docs/public/70-reference/17-supported-platforms.md',
  docsUrl: 'https://opensip.ai/docs/opensip-cli/70-reference/17-supported-platforms',
  notes: 'macOS 15 is not measured by this contract; may work, no promise.',
};

test('renders a supported row (post burn-in) with its evidence link and burn-in count', () => {
  const doc = renderSupportedPlatformsDoc([SUPPORTED_ROW], 1, 'v0.7.0');
  assert.match(doc, /`macos-26-arm64-node24-npm11-v1` \| `supported`/u);
  assert.match(doc, /Published evidence: https:\/\/example\.test\/evidence\/v0\.7\.0/u);
  assert.match(doc, /14 consecutive daily passes/u);
});

test('renders an unqualified row without a false promise and never as supported', () => {
  const doc = renderSupportedPlatformsDoc([UNQUALIFIED_ROW], 1, 'v0.7.0');
  assert.match(doc, /`macos-15-arm64-unqualified` \| `unqualified`/u);
  assert.doesNotMatch(doc, /`macos-15-arm64-unqualified` \| `supported`/u);
  assert.match(doc, /may work, no promise/u);
});

// ---------------------------------------------------------------------------
// The REAL built registry renders preview (never supported) before burn-in,
// and the committed public + web-generated docs stay in sync (write→check).
// ---------------------------------------------------------------------------

test('the real core registry renders preview and never a premature supported claim', () => {
  const doc = renderSupportedPlatformsDoc(
    PLATFORM_SUPPORT_ROWS,
    PLATFORM_SUPPORT_CONTRACT_VERSION,
    'v0.7.0',
  );
  assert.match(doc, /`macos-26-arm64-node24-npm11-v1` \| `preview`/u);
  assert.doesNotMatch(doc, /`macos-26-arm64-node24-npm11-v1` \| `supported`/u);
  // No row may claim supported until an external burn-in gate promotes it.
  for (const row of PLATFORM_SUPPORT_ROWS) {
    assert.notEqual(row.status, 'supported', `${row.id} must not be supported yet`);
  }
});

test('the committed public doc is byte-in-sync with the registry (check mode would fail on drift)', () => {
  // This is exactly what `pnpm docs:platform-support:check` compares: the
  // committed bytes vs. a deterministic render of the live registry. A registry
  // change (status, id, profile, evidence link) changes these bytes, so a
  // reviewer that forgets to regenerate is caught by the check gate.
  const rendered = renderSupportedPlatformsDoc(
    PLATFORM_SUPPORT_ROWS,
    PLATFORM_SUPPORT_CONTRACT_VERSION,
    releaseVersion(),
  );
  const committed = readFileSync(PUBLIC_DOC, 'utf8');
  assert.equal(committed, rendered, 'run `pnpm docs:platform-support` to regenerate the matrix');
});

test('a registry change necessarily changes the rendered bytes (drift is observable)', () => {
  const base = renderSupportedPlatformsDoc(PLATFORM_SUPPORT_ROWS, 1, 'v0.7.0');
  const drifted = renderSupportedPlatformsDoc(
    [{ ...PLATFORM_SUPPORT_ROWS[0], status: 'supported', ...SUPPORTED_ROW }],
    1,
    'v0.7.0',
  );
  assert.notEqual(base, drifted, 'a status change must change the generated bytes');
});

test('the web-generated mirror exists and the public matrix links compatibility/quick-start/FAQ', () => {
  assert.ok(existsSync(WEB_DOC), 'docs/web-generated must carry the generated matrix mirror');
  const committed = readFileSync(PUBLIC_DOC, 'utf8');
  assert.match(committed, /\.\/15-compatibility-policy\.md/u, 'links the compatibility policy');
  assert.match(committed, /\.\.\/00-start\/00-quick-start\.md/u, 'links Quick start');
  assert.match(committed, /\.\.\/00-start\/04-faq\.md/u, 'links the FAQ');
});

// ---------------------------------------------------------------------------
// Generator ↔ catalog single-source parity: the generated matrix and the core
// registry the CLI/MCP catalogs classify against expose the SAME facts.
// ---------------------------------------------------------------------------

test('generator and catalog registry agree on contract version, row ids, statuses, profiles, and evidence links', () => {
  const doc = renderSupportedPlatformsDoc(
    PLATFORM_SUPPORT_ROWS,
    PLATFORM_SUPPORT_CONTRACT_VERSION,
    'v0.7.0',
  );
  assert.match(
    doc,
    new RegExp(`contract version: \\*\\*${PLATFORM_SUPPORT_CONTRACT_VERSION}\\*\\*`, 'u'),
  );
  for (const row of PLATFORM_SUPPORT_ROWS) {
    assert.ok(doc.includes(`\`${row.id}\``), `matrix must list row id ${row.id}`);
    assert.ok(doc.includes(`\`${row.status}\``), `matrix must render status ${row.status}`);
    if (row.profile) {
      assert.ok(
        doc.includes(`\`${row.profile.id}\``),
        `matrix must cite profile ${row.profile.id}`,
      );
    }
    if (row.evidence?.url) {
      assert.ok(doc.includes(row.evidence.url), `matrix must publish evidence link for ${row.id}`);
    }
  }
});
